blog/app/socket/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms import SubmitField, StringField
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField
from ..models import User


class RoomForm(FlaskForm):
    name = StringField('Room name', validators=[DataRequired()])
    users = QuerySelectMultipleField(query_factory=lambda: User.query, get_label=lambda user: user.full_name(), blank_text='Select users...', allow_blank=False)
    submit = SubmitField('Create room')

blog/app/socket/__init__.py
from flask import Blueprint


socket = Blueprint('socket', __name__)


from . import views, events

blog/app/socket/views.py
from . import socket
from flask import render_template, request, current_app, flash, redirect, url_for, abort
from flask_login import current_user, login_required
from ..models import db, User, Room, RoomUserAssociation
from datetime import datetime, timedelta
from .forms import RoomForm


@socket.route('/rooms')
@login_required
def rooms():
    page = request.args.get('page', type=int, default=1)
    paginator = Room.query.paginate(page, per_page=current_app.config['FLASKY_USER_PER_PAGE'])
    return render_template('socket/rooms-page.html', rooms=paginator.items, paginator=paginator)


@socket.route('/new/room', methods=['GET', 'POST'])
@login_required
def create_room():
    print(request.form)
    form = RoomForm()
    if form.validate_on_submit():
        room = Room(name=form.name.data, author=current_user)
        room.room_users = [RoomUserAssociation(user=user, room=room) for user in [*form.users.data, current_user]]
        db.session.add(room)
        db.session.commit()
        flash('Your room has been created')
    return render_template('socket/create-room-page.html', form=form)


@socket.route('/show/room/<int:room_id>')
@login_required
def show_room(room_id):
    room = Room.query.get_or_404(room_id) if room_id is not None else None
    return render_template('socket/chat-page.html', current_room=room)


@socket.route('/delete/room/<int:room_id>', methods=['POST'])
@login_required
def delete_room(room_id):
    room = Room.query.filter_by(id=room_id).first_or_404()
    if room.is_author(current_user) or current_user.is_administrator():

        db.session.delete(room)
        db.session.commit()

        flash('The room has been deleted')
        return redirect(url_for('.rooms', _external=True))

    abort(401)


@socket.route('/online/users')
@login_required
def online_users():
    page = request.args.get('page', type=int, default=1)
    paginator = User.query.filter(User.last_seen > datetime.utcnow() - timedelta(minutes=10)) \
        .paginate(page, per_page=current_app.config['FLASKY_USER_PER_PAGE'])
    return render_template('socket/online-users-page.html', users=paginator.items, paginator=paginator)

blog/app/templates/socket/chat-page.html
{% extends "base-layout.html" %}
{% import "_macros.html" as macros %}

{% block content %}
<!-- Classic tabs -->
<div class="classic-tabs mx-2 pt-5">
    <ul class="nav tabs-info" id="js-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link  waves-light active show" id="js-chat-room-tab" data-toggle="tab"
               href="#js-chat-room-content"
               role="tab" aria-controls="js-chat-room" aria-selected="true">
                <i class="fas fa-home fa-2x pb-2"
                   aria-hidden="true"></i><br>Chat Room</a>
        </li>
        <li class="nav-item">
            <a class="nav-link waves-light" id="js-online-user-tab" data-toggle="tab"
               href="#js-online-user-content"
               role="tab" aria-controls="js-user-tab" aria-selected="false">
                <i class="fas fa-users fa-2x pb-2"
                   aria-hidden="true"></i><br>Online Users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link waves-light" id="js-user-tab" data-toggle="tab"
               href="#js-user-content"
               role="tab" aria-controls="follow-classic-orange" aria-selected="false">
                <i class="fas fa-users fa-2x pb-2"
                   aria-hidden="true"></i><br>Users</a>
        </li>
    </ul>

    <div class="tab-content card" id="js-tab-content">
        <div class="tab-pane fade active show" id="js-chat-room-content" role="tabpanel"
             aria-labelledby="profile-tab-classic-orange">
            <div class="chat-list-msg" id="scrollbar">
                <ul class="list-group list-group-flush" id="js-chat-room"></ul>
            </div>
            <div class="chat-form pt-4">
                <div class="form-group basic-textarea">
                    <textarea class="form-control pl-2 my-0" id="js-text" rows="3"
                              placeholder="Type your message here..." spellcheck="false"></textarea>
                </div>
                <button id="js-send-message" type="button"
                        class="btn btn-info btn-rounded btn-sm waves-effect waves-light float-right"> Send
                </button>
            </div>
        </div>
        <div class="tab-pane fade  chat-content" id="js-online-user-content" role="tabpanel"
             aria-labelledby="follow-tab-classic-orange">
            <ul class="list-group list-group-flush" id="js-users-in-room"></ul>
        </div>
        <div class="tab-pane fade  chat-content" id="js-user-content" role="tabpanel"
             aria-labelledby="contact-tab-classic-orange">
            <ul class="list-group list-group-flush">
                {% for user_room in current_room.room_users %}
                <li class="list-group-item"><a href="{{ url_for('auth.profile', username=user_room.user.username) }}">{{ user_room.user.full_name() }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<!-- Classic tabs -->
{% endblock content %}

{% block scripts %}
{{ super() }}
{% if current_room is not none %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.dev.js"></script>
<script type="text/javascript" charset="utf-8">
$( document ).ready(function() {
    const socket = io();
    const current_user = '{{ current_user.username }}';
    const current_room = '{{ current_room.id }}';

    socket.on('connect', function() {
        socket.emit('join', {room: current_room});
    });

    socket.on('status', function(message) {
        $(document).find("#js-users-in-room").append('<li class="list-group-item">'+ message +'</li>');
    });

    socket.on('text', function(data) {
        $(document).find("#js-chat-room").append('<li class="list-group-item"><strong>'+ data.user_full_name + '</strong> : ' + data.message +'</li>');
        $('#scrollbar').scrollTop($('#scrollbar')[0].scrollHeight);
    });

    $('#js-text').keypress(function(e) {
        const code = e.keyCode || e.which;
        if (code == 13) {
            const text = $('#js-text').val();
            $('#js-text').val("");
            socket.emit('message', {message: text, room: current_room});
        }
    });

    $('#js-send-message').click(function(e) {
        text = $('#js-text').val();
            $('#js-text').val('');
            socket.emit('message', {message: text, room: current_room});
    });
});

</script>
{% endif %}
{% endblock scripts %}

blog/app/templates/socket/create-room-page.html
{% extends "base-layout.html" %}
{% import "wtforms.html" as wtf %}

{% block content -%}
<!--Main layout-->
<main class="pt-10 center-row">

    <!--Grid column-->
    <div class="col-md-7 mb-4">

        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}

        {% if current_user.can(Permission.WRITE) %}
        <!-- Material form contact -->
        <div class="card">
            <h5 class="card-header info-color white-text text-center py-4">
                <strong>Create your chat room</strong>
            </h5>

            <!--Card content-->
            <div class="card-body px-lg-5 pt-4">
                <!-- Form -->
                {{ wtf.form_start(form) }}

                <!-- Name -->
                {{ wtf.form_field(form.name) }}

                <!-- Users -->
                {{ wtf.form_field(form.users) }}

                <!-- Send button -->
                {{ wtf.form_field(form.submit, field_class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4
                waves-effect") }}

                {{ wtf.form_end() }}
                <!-- Form -->

            </div>

        </div>
        <!-- Material form contact -->
        {% endif %}
    </div>
    <!--Grid column-->
</main>
<!--Main layout-->
{% endblock %}

blog/app/templates/socket/online-users-page.html
{% extends "base-layout.html" %}
{% import "_macros.html" as macros %}

{% block content %}
    <div class="row">
        {% for user in users -%}
        <div class="col-md-4 mb-4">
            <!-- Card Narrower -->
            <div class="card card-cascade narrower">

                <!-- Card image -->
                <div class="view view-cascade overlay">
                    <img class="card-img-top" src="{{ user.gravatar(size=300) }}"
                         alt="Card image cap">
                    <a>
                        <div class="mask rgba-white-slight"></div>
                    </a>
                </div>

                <!-- Card content -->
                <div class="card-body card-body-cascade">

                    <!-- Title -->
                    <h4 class="card-title"><a href="{{ url_for('blog.user_posts', username=user.username) }}"><strong>{{ '%s %s' % (user.first_name, user.last_name) }}</strong></a></h4>
                    <!-- Subtitle -->
                    <h6 class="font-weight-bold indigo-text py-2">Last Seen {{ moment(user.last_seen).fromNow() }}</h6>
                    <!-- Text -->
                    <p class="card-text">{% if user.about_me is not none %} {{ user.about_me|truncate(100) | safe }} {% else
                        %} ---- {% endif %}</p>
                    <!-- Button -->
                    <a href="{{ url_for('blog.follow_user', username=user.username) }}"
                       class="btn btn-info btn-rounded btn-md"> <i class="fas fa-paper-plane pr-2"></i>
                        send message </a>
                </div>

                {% if current_user.is_administrator() %}
                <!-- Card footer -->
                <div class="card-footer text-muted text-center">
                    <div class="d-flex">
                        <div>
                            <a href=""
                               class="btn btn-success btn-rounded btn-sm px-3 waves-effect waves-light">
                                <i class="fas fa-edit pr-2"></i> Edit
                            </a>
                        </div>
                        <div class="ml-auto">
                            <a href=""
                               class="btn btn-danger btn-rounded btn-sm px-3 waves-effect waves-light">
                                <i class="fas fa-trash pr-2"></i> Delete
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
            <!-- Card Narrower -->
        </div>
        {% else %}
        <div class="col-md-12">
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading">Oops!</h4>
                <p>No result found.</p>
                <hr>
                <p class="mb-0">If you notice this notice you will notice this notice is not worth noticing.</p>
            </div>
        </div>
        {% endfor %}
    </div>

    {{ macros.pagination_widget(paginator, 'socket.online_users') }}
{% endblock content %}

blog/app/templates/socket/rooms-page.html
{% extends "base-layout.html" %}
{% import "_macros.html" as macros %}

{% block content %}

<div class="row pt-4">
    {% for room in rooms -%}
    <!--  Grid column  -->
    <div class="col-lg-4 col-md-6 mb-4">

        <!-- Card -->
        <div class="pricing-card card">

            <!-- Pricing card -->
            <div class="text-center pricing-card d-flex align-items-center rgba-info-strong pt-2 rounded">
                <!-- Content -->
                <div class="card-body">
                    <h5 class="font-weight-bold"><i class="fas fa-home"></i> {{ room.name|capitalize }}</h5>
                    <hr>
                    <p><strong>{{ room.online_users()|length }}</strong> Offline Users</p>
                    <hr>
                    <p><strong>{{ room.offline_users()|length }}</strong> Online Users</p>
                    <hr>
                    <a href="{{ url_for('socket.show_room', room_id=room.id) }}" class="btn btn-info btn-rounded btn-sm px-3 waves-effect waves-light"> Enter the room </a>
                    {{ macros.delete_form('socket.delete_room', room_id=room.id) }}
                </div>
                <!-- Content -->

            </div>
            <!-- Pricing card -->

        </div>
        <!-- Card -->
    </div>
    <!-- Grid column -->
    {% else %}
    <div class="col-md-12">
        <div class="alert alert-info" role="alert">
            <h4 class="alert-heading">Oops!</h4>
            <p>No result found.</p>
            <hr>
            <p class="mb-0">If you notice this notice you will notice this notice is not worth noticing.</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}