blog/app/blog/forms.py
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, Email
from flask_wtf.file import FileField, FileRequired
from flask_wtf import FlaskForm


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = TextAreaField(None, render_kw={'id': 'js-markdown-field'}, validators=[DataRequired(), Length(max=4000)])
    file = FileField('Post Image', validators=[FileRequired()])
    submit = SubmitField('Post')


class CommentForm(FlaskForm):
    body = TextAreaField('Write your comment here ...', validators=[DataRequired(), Length(max=500)])
    submit = SubmitField('Post')

blog/app/blog/__init__.py
from flask import Blueprint
from ..models import Permission


blog = Blueprint('blog', __name__)
from . import views

blog/app/blog/views.py
from flask import render_template, flash, current_app, request, redirect, url_for, abort
from flask_login import login_required, current_user
from . import blog
from .. import db, uploads
from ..models import Post, User, Follow, Comment, Permission
from .forms import PostForm, CommentForm
from ..decorators import permission_required_in, permission_required_eq
from os import remove


@blog.route('/', methods=['GET', 'POST'])
def index_posts():
    page = request.args.get('page', 1, type=int)
    paginator = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'], error_out=False)
    return render_template('blog/posts-page.html', posts=paginator.items, paginator=paginator)


@blog.route('/<string:username>/posts', methods=['GET'])
def user_posts(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    paginator = Post.query.filter_by(author_id=user.id).order_by(Post.timestamp.desc()).paginate(page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'], error_out=False)
    return render_template('blog/user-posts-page.html', user=user, posts=paginator.items, paginator=paginator)


@blog.route('/show/post/<int:identifier>', methods=['GET', 'POST'])
def show_post(identifier):
    post = Post.query.filter_by(id=identifier).first_or_404()
    page = request.args.get('page', 1, type=int)
    form = CommentForm()
    if form.validate_on_submit() and current_user.can(Permission.COMMENT):
        comment = Comment(author=current_user, body=form.body.data, post=post)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment is created')
        return redirect(url_for('.show_post', identifier=post.id, _external=True))

    paginator = db.session.query(Comment).filter_by(post=post, disabled=False).paginate(page, per_page=current_app.config['FLASKY_COMMENT_PER_PAGE'], error_out=False)

    return render_template('blog/show-post-page.html', form=form, post=post, comments=paginator.items, paginator=paginator)


@blog.route('/delete/post/<int:identifier>', methods=['POST'])
@login_required
def delete_post(identifier):
    post = Post.query.filter_by(id=identifier).first_or_404()
    if post.is_author(current_user) or current_user.is_administrator():

        db.session.delete(post)
        db.session.commit()
        if post.image_filename is not None:
            remove(uploads.path(post.image_filename))

        flash('The post has been deleted')
        return redirect(url_for('.index_posts', _external=True))

    abort(401)


@blog.route('/edit/post/<int:identifier>', methods=['POST', 'GET'])
@login_required
def edit_post(identifier):
    post = Post.query.filter_by(id=identifier).first_or_404()
    if not post.is_author(current_user) and not current_user.is_administrator():
        abort(401)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.image_filename = uploads.save(form.file.data)
        flash('The post has been updated')
        db.session.commit()
        return redirect(url_for('.show_post', identifier=post.id))

    form.title.data = post.title
    form.body.data = post.body
    form.file.data = post.image_filename

    return render_template('blog/edit-post-page.html', form=form)


@blog.route('/new/post', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        filename = uploads.save(form.file.data)
        post = Post(title=form.title.data, body=form.body.data, image_filename=filename, author=current_user._get_current_object())
        db.session.add(post)
        db.session.commit()
        flash('Your Post is created')
        return redirect(url_for('.index_posts'))

    return render_template('blog/new-post-page.html', form=form)


@blog.route('/followers/<string:username>')
@login_required
def followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    paginator = db.session.query(User). \
        filter(Follow.follower_id == user.id). \
        join(Follow, Follow.followed_id == User.id). \
        order_by(Follow.timestamp.desc()). \
        paginate(page, per_page=current_app.config['FLASKY_FOLLOWER_PER_PAGE'], error_out=True)
    return render_template('blog/user-followers-page.html', user=user, followers=paginator.items, paginator=paginator)


@blog.route('/following/<string:username>')
@login_required
def following(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    paginator = db.session.query(User). \
        filter(Follow.followed_id == user.id). \
        join(Follow, Follow.follower_id == User.id). \
        order_by(Follow.timestamp.desc()). \
        paginate(page, per_page=current_app.config['FLASKY_FOLLOWED_PER_PAGE'], error_out=True)
    return render_template('blog/user-following-page.html', user=user, following=paginator.items, paginator=paginator)


@blog.route('/follow/<string:username>')
@login_required
@permission_required_eq(Permission.FOLLOW)
def follow_user(username):
    user_to_follow = User.query.filter_by(username=username).first_or_404()

    if not current_user.is_following(user_to_follow):
        follow_object = Follow(follower_id=user_to_follow.id, followed_id=current_user.id)
        db.session.add(follow_object)
        db.session.commit()
        flash('You are now following %s.' % username)
    else:
        flash('You are already following this user.')

    return redirect(url_for('.following', username=current_user.username))


@blog.route('/un-follow/<string:username>')
@login_required
@permission_required_eq(Permission.FOLLOW)
def un_follow_user(username):
    user_to_un_follow = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user_to_un_follow):
        follow_object = Follow.query.filter_by(follower_id=user_to_un_follow.id, followed_id=current_user.id).first()
        db.session.delete(follow_object)
        db.session.commit()
        flash('You are now not following %s.' % username)
    else:
        flash('You are already not following this user.')

    return redirect(url_for('.following', username=current_user.username))


@blog.route('/comment/edit/<int:identifier>', methods=['GET', 'POST'])
@login_required
@permission_required_in(Permission.ADMIN, Permission.MODERATE)
def edit_comment(identifier):
    comment = Comment.query.filter_by(id=identifier).first_or_404()
    page = request.args.get('page', 1, type=int)
    form = CommentForm()
    if form.validate_on_submit() and current_user.can(Permission.COMMENT):
        comment.body = form.body.data
        db.session.add(comment)
        db.session.commit()
        flash('Your comment is updated')
        return redirect(url_for('.show_post', identifier=comment.post_id))

    form.body.data = comment.body

    paginator = db.session.query(Comment).filter_by(post=comment.post, disabled=False).\
        paginate(page, per_page=current_app.config['FLASKY_COMMENT_PER_PAGE'], error_out=False)

    return render_template('blog/show-post-page.html', scroll='js-comment-section', form=form, post=comment.post, comments=paginator.items,
                           paginator=paginator)


@blog.route('/comment/disable/<int:identifier>', methods=['POST'])
@login_required
@permission_required_in(Permission.ADMIN, Permission.MODERATE)
def disable_comment(identifier):
    comment = Comment.query.get_or_404(identifier)
    if not comment.disabled:
        comment.disabled = True
        db.session.commit()
        flash('This comment is disabled')
    else:
        flash('This comment is already disabled')

    return redirect(url_for('.show_post', identifier=comment.post_id))


@blog.route('/comment/enable/<int:identifier>', methods=['POST'])
@login_required
@permission_required_in(Permission.ADMIN, Permission.MODERATE)
def enable_comment(identifier):
    comment = Comment.query.get_or_404(identifier)
    if comment.disabled:
        comment.disabled = False
        db.session.commit()
        flash('This comment is enabled')
    else:
        flash('This comment is already enabled')

    return redirect(url_for('.show_post', identifier=comment.post_id))

blog/app/templates/blog/edit-post-page.html
{% extends "base-layout.html" %}
{% import "wtforms.html" as wtf %}

{% block title %}Edit Blog{% endblock title %}

{%- block styles %}
{{ super() }}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock styles %}

{% block content -%}
<!--Main layout-->
<main class="pt-10 center-row">

    <!--Grid column-->
    <div class="col-md-7 mb-4">

        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}

        {% if current_user.can(Permission.WRITE) %}
        <!-- Material form contact -->
        <div class="card">

            <h5 class="card-header info-color white-text text-center py-4">
                <strong>What's on your mind ?</strong>
            </h5>

            <!--Card content-->
            <div class="card-body px-lg-5 pt-4">
                <!-- Form -->
                {{ wtf.form_start(form) }}

                <!-- File -->
                {{ wtf.form_field(form.file) }}

                <!-- Title -->
                {{ wtf.form_field(form.title) }}

                <!-- Body -->
                {{ form.body() }}

                <!-- Send button -->
                {{ wtf.form_field(form.submit, field_class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4
                waves-effect") }}

                {{ wtf.form_end() }}
                <!-- Form -->

            </div>

        </div>
        <!-- Material form contact -->
        {% endif %}
    </div>
    <!--Grid column-->
</main>
<!--Main layout-->
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
  function readURL(input, img) {
     if (input.files && input.files[0]) {
       var reader = new FileReader();
       reader.onload = function(e) {
         img.attr('src', e.target.result);
       }
       reader.readAsDataURL(input.files[0]);
     }
   }
   $(document).on("change", "input[type='file']", function() {
     readURL(this, $(this).parents('div .file-field').find(".img-preview"));
   });

  new SimpleMDE({ element: document.getElementById("js-markdown-field") });


</script>
{% endblock %}

blog/app/templates/blog/new-post-page.html
{% extends "base-layout.html" %}
{% import "wtforms.html" as wtf %}

{% block title %}Contact{% endblock title %}

{%- block styles %}
{{ super() }}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock styles %}

{% block content -%}
<!--Main layout-->
<main class="pt-10 center-row">

    <!--Grid column-->
    <div class="col-md-7 mb-4">

        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}

        {% if current_user.can(Permission.WRITE) %}
        <!-- Material form contact -->
        <div class="card">
            <h5 class="card-header info-color white-text text-center py-4">
                <strong>What's on your mind ?</strong>
            </h5>

            <!--Card content-->
            <div class="card-body px-lg-5 pt-4">
                <!-- Form -->
                {{ wtf.form_start(form) }}

                <!-- File -->
                {{ wtf.form_field(form.file) }}

                <!-- Title -->
                {{ wtf.form_field(form.title) }}
                <!-- Body -->
                {{ form.body() }}
                <!-- Send button -->
                {{ wtf.form_field(form.submit, field_class="btn btn-outline-info btn-rounded btn-block z-depth-0 my-4
                waves-effect") }}

                {{ wtf.form_end() }}
                <!-- Form -->

            </div>

        </div>
        <!-- Material form contact -->
        {% endif %}
    </div>
    <!--Grid column-->
</main>
<!--Main layout-->
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
  new SimpleMDE({ element: document.getElementById("js-markdown-field") });
</script>
{% endblock %}

blog/app/templates/blog/posts-page.html
{% extends "base-layout.html" %}
{% import "wtforms.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Blog{% endblock title %}

{% block content %}
<!-- Section: Blog v.3 -->
<section class="pt-10 row">
    {% for post in posts %}
    <div class="col-sm-4 mb-4">
        <!-- Card -->
        <div class="card promoting-card">

            <!-- Card image -->
            <div class="view overlay">
                <img class="card-img-top post-img rounded-0"
                     src="{% if post.image_filename %}{{ render_uploaded_file_url(filename=post.image_filename, height=250) }}{% else %}{{url_for('static', filename='img/no-image-icon.png')}}{% endif %}" alt="Card image cap">
                <a href="{{ url_for('blog.show_post', identifier=post.id) }}">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>

            <!-- Button -->
            <a  href="{{ url_for('blog.show_post', identifier=post.id) }}" class="btn-floating btn-action ml-auto mr-4 mdb-color red-text lighten-3"><i
                    class="fas fa-chevron-right pl-1"></i></a>

            <!-- Card content -->
            <div class="card-body">

                <div class="collapse-content pt-3">

                    <!-- Title -->
                    <h4 class="card-title font-weight-bold mb-2">{{ post.title|truncate(40) }}</h4>

                    <!-- Text -->
                    <p class="card-text collapse" id="js-read-more-{{ post.id }}">{{ post.body|truncate(300) }}</p>
                    <!-- Button -->
                    <a class="btn btn-flat red-text p-1 my-1 mr-0 mml-1 collapsed" data-toggle="collapse"
                       href="#js-read-more-{{ post.id }}" aria-expanded="false" aria-controls="collapseContent"></a>

                </div>


                    <!-- Subtitle -->
                    <p class="card-text pt-1 pb-0 mb-0">
                        <i class="far fa-user pr-2"></i> By <a
                            href="{{ url_for('auth.profile', username=post.author.username) }}"
                            class="font-weight-bold">{{ post.author.full_name() }}</a></p>
                    <p class="card-text"><i class="far fa-clock pr-2"></i> In {{ moment(post.timestamp).fromNow() }}</p>

            </div>

            {% if post.is_author(current_user) or current_user.is_administrator() %}
            <!-- Card footer -->
            <div class="card-footer text-muted text-center">
                    <div class="d-flex">
                        <div>
                            <a href="{{ url_for('blog.edit_post', identifier=post.id) }}"
                               class="btn btn-success btn-rounded btn-sm px-3 waves-effect waves-light">
                                <i class="fas fa-edit pr-2"></i> Edit
                            </a>
                        </div>
                        <div class="ml-auto">
                            {{ macros.delete_form('blog.delete_post', identifier=post.id) }}
                        </div>
                    </div>
            </div>
            {% endif %}

        </div>
        <!-- Card -->
    </div>
    {% endfor %}

    <div class="col-12">
        {{ macros.pagination_widget(paginator, 'blog.index_posts') }}
    </div>
</section>
<!-- Section: Blog v.3 -->
{% endblock content %}

blog/app/templates/blog/show-post-page.html
{% extends "base-layout.html" %}
{% import "wtforms.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content -%}
<!--Grid row-->
<div class="pt-10 pb-5 center-row">
    <!--Grid column-->
    <div class="col-md-12 px-lg-5">
        <!--Card-->
        <div class="card pb-5 mx-md-3">

            <div class="card-body">

                <div class="container">

                    <!--Section heading-->
                    <h1 class="text-center h1 pt-4 mb-3">
                        <strong>{{ post.title }}</strong>
                    </h1>

                    <!--Grid row-->
                    <div class="row pt-lg-5 pt-3">
                        <div class="col-md-12 my-4 center-row">
                            <img src="{{ render_uploaded_file_url(filename=post.image_filename) }}"
                                 class="img-fluid z-depth-1 rounded-0" alt="sample image">
                        </div>
                        <!--Grid column-->
                        <div class="col-md-12 col-xl-12 pt-5">

                            <p class="dark-grey-text article">{{ post.body }}</p>

                            <hr class="mt-5">

                            <!-- Grid column -->
                            <div class="col-lg-12 d-md-flex">
                                <div class="avatar mb-md-0 mb-4 mx-4">
                                    <img src="{{ post.author.gravatar(size=100) }}"
                                         class="rounded rounded-circle z-depth-1" alt="Sample avatar">
                                </div>
                                <div class="mx-4">
                                    <h4 class="font-weight-bold mb-3">By {{ post.author.full_name() }}</h4>
                                    <h6 class="font-weight-bold grey-text mb-3"> In {{ moment(post.timestamp).fromNow() }}</h6>
                                    <p class="grey-text">{{ post.author.about_me|truncate(200) }}</p>
                                    <!-- Read more button -->
                                    <a href="{{ url_for('auth.profile', username=post.author.username) }}" class="btn btn-transparent btn-sm font-weight-bold btn-rounded dark-grey-text waves-effect waves-light">Read more</a>

                                </div>
                            </div>
                            <!-- Grid column -->

                            <hr class="mt-3">

                            <!--Comments-->
                            <section>

                                <!--Main wrapper-->
                                <div class="comments-list text-center text-md-left">
                                    <div class="text-center my-5">
                                        <h3 class="font-weight-bold">Comments
                                        </h3>
                                    </div>

                                    {% for comment in post.comments if (current_user.can(Permission.ADMIN) or current_user.can(Permission.MODERATE)) or ( not current_user.can(Permission.ADMIN) and not current_user.can(Permission.MODERATE) and not comment.disabled) %}
                                    <!--First row-->
                                    <div class="row mb-5">
                                        <!--Image column-->
                                        <div class="col-sm-2 col-12 mb-3">
                                            <img src="{{ comment.author.gravatar(size=150) }}" class="avatar rounded-circle z-depth-1-half" alt="sample image">
                                        </div>
                                        <!--/.Image column-->

                                        <!--Content column-->
                                        <div class="col-sm-10 col-12">
                                            <a>
                                                <h5 class="user-name font-weight-bold">{{ comment.author.full_name() }}</h5>
                                            </a>
                                            <div class="card-data">
                                                <ul class="list-unstyled">
                                                    <li class="comment-date font-small">
                                                        <i class="far fa-clock-o"></i> Last Seen {{ moment(comment.author.last_seen).fromNow() }}
                                                    </li>
                                                </ul>
                                            </div>

                                            <p class="dark-grey-text article">{{ comment.body }}  {% if comment.disabled %}<span class="badge badge-pill text-sm badge-danger text-monospace">Disabled</span>{% endif %}</p>


                                            {% if current_user.can(Permission.ADMIN) or current_user.can(Permission.MODERATE) %}
                                                <a href="{{ url_for('blog.edit_comment', identifier=comment.id) }}" class="btn btn-success btn-sm font-weight-bold btn-rounded waves-effect waves-light">Edit comment</a>
                                                {{ macros.delete_form( 'blog.enable_comment' if comment.disabled else 'blog.disable_comment', identifier=comment.id, button_name='Enable comment' if comment.disabled else 'Disable comment', msg='Are you sure you want to disable this comment ?' ) }}

                                            {% endif %}

                                        </div>
                                        <!--/.Content column-->
                                    </div>
                                    <!--/.First row-->
                                    {% endfor %}

                                    {{ macros.pagination_widget(paginator, 'blog.show_post', identifier=post.id) }}
                                </div>
                                <!--/.Main wrapper-->

                            </section>

                            {% if current_user.can(Permission.COMMENT) %}
                                <!--/Comments-->
                                <hr id="js-comment-section">
                                <!--Section: Leave a reply (Not Logged In User)-->
                                <section class="mb-4 wow fadeIn" data-wow-delay="0.2s">
                                    <h3 class="font-weight-bold text-center my-5">Leave a reply</h3>
                                    {{ wtf.form_start(form) }}
                                    {{ wtf.form_field(form.body) }}
                                    {{ wtf.form_field(form.submit, field_class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0") }}
                                    {{ wtf.form_end() }}
                                </section>
                                <!--/Section: Leave a reply (Not Logged In User)-->
                            {% endif %}

                        </div>
                        <!--/Grid column-->

                    </div>
                    <!--/Grid row-->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </div>
        <!--/Card-->
    </div>
    <!--/Grid column-->
</div>
<!--/Grid row-->
{% endblock content %}

blog/app/templates/blog/user-followers-page.html
{% extends "profile-layout.html" %}
{% import '_macros.html' as marcos %}

{% block profile_content -%}
    {% for follower in followers %}
    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-lg-2 col-xl-2">

            <!-- Featured image -->
            <div class="view overlay rounded z-depth-1-half mb-4 z-depth-1 rounded-circle">
                <img class="img-fluid post-img"
                     src="{{ follower.gravatar(size=300) }}"
                     alt="Sample image">
                <a>
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-lg-10 col-xl-10">

            <!-- Post title -->
            <h3 class="font-weight-bold mb-3"><strong>{{ follower.full_name() }}</strong></h3>
            <!-- Excerpt -->
            <p class="dark-grey-text">{{ follower.about_me|truncate(300) | safe }}</p>
            <!-- Read more button -->
            <a href="{{ url_for('auth.profile', username=follower.username) }}" class="btn btn-info btn-rounded btn-md">
                <i class="fas fa-book pr-2"></i> View profile
            </a>

        </div>
        <!-- Grid column -->

    </div>
    <!-- Grid row -->

    <hr class="my-4">
    {% else %}
        <div class="col-md-12">
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading">Oops!</h4>
                <p>No result found.</p>
                <hr>
                <p class="mb-0">If you notice this notice you will notice this notice is not worth noticing.</p>
            </div>
        </div>
    {% endfor %}

    {{ macros.pagination_widget(paginator, 'blog.followers', username=user.username) }}
{% endblock %}

blog/app/templates/blog/user-following-page.html
{% extends "profile-layout.html" %}

{% block profile_content -%}
    {% for follower in following %}
    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-lg-2 col-xl-2">

            <!-- Featured image -->
            <div class="view overlay rounded z-depth-1-half mb-4 z-depth-1 rounded-circle">
                <img class="img-fluid post-img"
                     src="{{ follower.gravatar(size=300) }}"
                     alt="Sample image">
                <a>
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-lg-10 col-xl-10">

            <!-- Post title -->
            <h3 class="font-weight-bold mb-3"><strong>{{ follower.full_name() }}</strong></h3>
            <!-- Excerpt -->
            <p class="dark-grey-text">{{ follower.about_me|truncate(300) | safe }}</p>
            <!-- Read more button -->
            <a href="{{ url_for('auth.profile', username=follower.username) }}" class="btn btn-info btn-rounded btn-md">
                <i class="fas fa-book pr-2"></i> View profile
            </a>

        </div>
        <!-- Grid column -->

    </div>
    <!-- Grid row -->

    <hr class="my-4">
    {% else %}
        <div class="col-md-12">
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading">Oops!</h4>
                <p>No result found.</p>
                <hr>
                <p class="mb-0">If you notice this notice you will notice this notice is not worth noticing.</p>
            </div>
        </div>
    {% endfor %}

    {{ macros.pagination_widget(paginator, 'blog.following', username=user.username) }}
{% endblock %}

blog/app/templates/blog/user-posts-page.html
{% extends "profile-layout.html" %}

{% block profile_content %}
    {% include '_post.html' %}

    {{ macros.pagination_widget(paginator, 'blog.index_posts') }}
{% endblock profile_content %}